export const genshinCharacters = {
    "Albedo": {Quality: "5", Element: "Geo", Weapon: "Sword", Region: "Mondstadt", Gender: "Male", Version: "1.2"},
    "Alhaitham": {Quality: "5", Element: "Dendro", Weapon: "Sword", Region: "Sumeru", Gender: "Male", Version: "3.4"},
    "Aloy": {Quality: "5", Element: "Cryo", Weapon: "Bow", Region: "None", Gender: "Female", Version: "2.1"},
    "Amber": {Quality: "4", Element: "Pyro", Weapon: "Bow", Region: "Mondstadt", Gender: "Female", Version: "1.0"},
    "Arataki Itto": {Quality: "5", Element: "Geo", Weapon: "Claymore", Region: "Inazuma", Gender: "Male", Version: "2.3"},
    "Arlecchino": {Quality: "5", Element: "Pyro", Weapon: "Polearm", Region: "Snezhnaya", Gender: "Female", Version: "4.6"},
    "Baizhu": {Quality: "5", Element: "Dendro", Weapon: "Catalyst", Region: "Liyue", Gender: "Male", Version: "3.6"},
    "Barbara": {Quality: "4", Element: "Hydro", Weapon: "Catalyst", Region: "Mondstadt", Gender: "Female", Version: "1.0"},
    "Beidou": {Quality: "4", Element: "Electro", Weapon: "Claymore", Region: "Liyue", Gender: "Female", Version: "1.0"},
    "Bennett": {Quality: "4", Element: "Pyro", Weapon: "Sword", Region: "Mondstadt", Gender: "Male", Version: "1.0"},
    "Candace": {Quality: "4", Element: "Hydro", Weapon: "Polearm", Region: "Sumeru", Gender: "Female", Version: "3.1"},
    "Charlotte": {Quality: "4", Element: "Cryo", Weapon: "Catalyst", Region: "Fontaine", Gender: "Female", Version: "4.2"},
    "Chasca": {Quality: "5", Element: "Anemo", Weapon: "Bow", Region: "Natlan", Gender: "Female", Version: "5.2"},
    "Chevreuse": {Quality: "4", Element: "Pyro", Weapon: "Polearm", Region: "Fontaine", Gender: "Female", Version: "4.3"},
    "Chiori": {Quality: "5", Element: "Geo", Weapon: "Sword", Region: "Inazuma", Gender: "Female", Version: "4.5"},
    "Chongyun": {Quality: "4", Element: "Cryo", Weapon: "Claymore", Region: "Liyue", Gender: "Male", Version: "1.0"},
    "Citlali": {Quality: "5", Element: "Cryo", Weapon: "Catalyst", Region: "Natlan", Gender: "Female", Version: "5.3"},
    "Clorinde": {Quality: "5", Element: "Electro", Weapon: "Sword", Region: "Fontaine", Gender: "Female", Version: "4.7"},
    "Collei": {Quality: "4", Element: "Dendro", Weapon: "Bow", Region: "Sumeru", Gender: "Female", Version: "3.0"},
    "Cyno": {Quality: "5", Element: "Electro", Weapon: "Polearm", Region: "Sumeru", Gender: "Male", Version: "3.1"},
    "Dehya": {Quality: "5", Element: "Pyro", Weapon: "Claymore", Region: "Sumeru", Gender: "Female", Version: "3.5"},
    "Diluc": {Quality: "5", Element: "Pyro", Weapon: "Claymore", Region: "Mondstadt", Gender: "Male", Version: "1.0"},
    "Diona": {Quality: "4", Element: "Cryo", Weapon: "Bow", Region: "Mondstadt", Gender: "Female", Version: "1.1"},
    "Dori": {Quality: "4", Element: "Electro", Weapon: "Claymore", Region: "Sumeru", Gender: "Female", Version: "3.0"},
    "Emilie": {Quality: "5", Element: "Dendro", Weapon: "Polearm", Region: "Fontaine", Gender: "Female", Version: "4.8"},
    "Eula": {Quality: "5", Element: "Cryo", Weapon: "Claymore", Region: "Mondstadt", Gender: "Female", Version: "1.5"},
    "Faruzan": {Quality: "4", Element: "Anemo", Weapon: "Bow", Region: "Sumeru", Gender: "Female", Version: "3.3"},
    "Fischl": {Quality: "4", Element: "Electro", Weapon: "Bow", Region: "Mondstadt", Gender: "Female", Version: "1.0"},
    "Freminet": {Quality: "4", Element: "Cryo", Weapon: "Claymore", Region: "Fontaine", Gender: "Male", Version: "4.0"},
    "Furina": {Quality: "5", Element: "Hydro", Weapon: "Sword", Region: "Fontaine", Gender: "Female", Version: "4.2"},
    "Gaming": {Quality: "4", Element: "Pyro", Weapon: "Claymore", Region: "Liyue", Gender: "Male", Version: "4.4"},
    "Ganyu": {Quality: "5", Element: "Cryo", Weapon: "Bow", Region: "Liyue", Gender: "Female", Version: "1.2"},
    "Gorou": {Quality: "4", Element: "Geo", Weapon: "Bow", Region: "Inazuma", Gender: "Male", Version: "2.3"},
    "Hu Tao": {Quality: "5", Element: "Pyro", Weapon: "Polearm", Region: "Liyue", Gender: "Female", Version: "1.3"},
    "Jean": {Quality: "5", Element: "Anemo", Weapon: "Sword", Region: "Mondstadt", Gender: "Female", Version: "1.0"},
    "Kachina": {Quality: "4", Element: "Geo", Weapon: "Polearm", Region: "Natlan", Gender: "Female", Version: "5.0"},
    "Kaedehara Kazuha": {Quality: "5", Element: "Anemo", Weapon: "Sword", Region: "Inazuma", Gender: "Male", Version: "1.6"},
    "Kaeya": {Quality: "4", Element: "Cryo", Weapon: "Sword", Region: "Mondstadt", Gender: "Male", Version: "1.0"},
    "Kamisato Ayaka": {Quality: "5", Element: "Cryo", Weapon: "Sword", Region: "Inazuma", Gender: "Female", Version: "2.0"},
    "Kamisato Ayato": {Quality: "5", Element: "Hydro", Weapon: "Sword", Region: "Inazuma", Gender: "Male", Version: "2.6"},
    "Kaveh": {Quality: "4", Element: "Dendro", Weapon: "Claymore", Region: "Sumeru", Gender: "Male", Version: "3.6"},
    "Keqing": {Quality: "5", Element: "Electro", Weapon: "Sword", Region: "Liyue", Gender: "Female", Version: "1.0"},
    "Kinich": {Quality: "5", Element: "Dendro", Weapon: "Claymore", Region: "Natlan", Gender: "Male", Version: "5.0"},
    "Kirara": {Quality: "4", Element: "Dendro", Weapon: "Sword", Region: "Inazuma", Gender: "Female", Version: "3.7"},
    "Klee": {Quality: "5", Element: "Pyro", Weapon: "Catalyst", Region: "Mondstadt", Gender: "Female", Version: "1.0"},
    "Kujou Sara": {Quality: "4", Element: "Electro", Weapon: "Bow", Region: "Inazuma", Gender: "Female", Version: "2.1"},
    "Kuki Shinobu": {Quality: "4", Element: "Electro", Weapon: "Sword", Region: "Inazuma", Gender: "Female", Version: "2.7"},
    "Layla": {Quality: "4", Element: "Cryo", Weapon: "Sword", Region: "Sumeru", Gender: "Female", Version: "3.2"},
    "Lisa": {Quality: "4", Element: "Electro", Weapon: "Catalyst", Region: "Mondstadt", Gender: "Female", Version: "1.0"},
    "Lynette": {Quality: "4", Element: "Anemo", Weapon: "Sword", Region: "Fontaine", Gender: "Female", Version: "4.0"},
    "Lyney": {Quality: "5", Element: "Pyro", Weapon: "Bow", Region: "Fontaine", Gender: "Male", Version: "4.0"},
    "Mavuika": {Quality: "5", Element: "Pyro", Weapon: "Claymore", Region: "Natlan", Gender: "Female", Version: "5.3"},
    "Mika": {Quality: "4", Element: "Cryo", Weapon: "Polearm", Region: "Mondstadt", Gender: "Male", Version: "3.5"},
    "Mona": {Quality: "5", Element: "Hydro", Weapon: "Catalyst", Region: "Mondstadt", Gender: "Female", Version: "1.0"},
    "Mualani": {Quality: "5", Element: "Hydro", Weapon: "Catalyst", Region: "Natlan", Gender: "Female", Version: "5.0"},
    "Nahida": {Quality: "5", Element: "Dendro", Weapon: "Catalyst", Region: "Sumeru", Gender: "Female", Version: "3.2"},
    "Navia": {Quality: "5", Element: "Geo", Weapon: "Claymore", Region: "Fontaine", Gender: "Female", Version: "4.4"},
    "Neuvillette": {Quality: "5", Element: "Hydro", Weapon: "Catalyst", Region: "Fontaine", Gender: "Male", Version: "4.1"},
    "Nilou": {Quality: "5", Element: "Hydro", Weapon: "Sword", Region: "Sumeru", Gender: "Female", Version: "3.1"},
    "Ningguang": {Quality: "5", Element: "Geo", Weapon: "Catalyst", Region: "Liyue", Gender: "Female", Version: "1.0"},
    "Noelle": {Quality: "4", Element: "Geo", Weapon: "Claymore", Region: "Mondstadt", Gender: "Female", Version: "1.1"},
    "Ororon": {Quality: "5", Element: "Electro", Weapon: "Bow", Region: "Natlan", Gender: "Male", Version: "5.2"},
    "Qiqi": {Quality: "4", Element: "Cryo", Weapon: "Sword", Region: "Liyue", Gender: "Female", Version: "1.0"},
    "Raiden Shogun": {Quality: "5", Element: "Electro", Weapon: "Polearm", Region: "Inazuma", Gender: "Female", Version: "2.1"},
    "Razor": {Quality: "4", Element: "Electro", Weapon: "Claymore", Region: "Mondstadt", Gender: "Male", Version: "1.0"},
    "Rosaria": {Quality: "4", Element: "Cryo", Weapon: "Polearm", Region: "Mondstadt", Gender: "Female", Version: "1.0"},
    "Sangonomiya Kokomi": {Quality: "5", Element: "Hydro", Weapon: "Catalyst", Region: "Inazuma", Gender: "Female", Version: "2.0"},
    "Sayu": {Quality: "4", Element: "Anemo", Weapon: "Claymore", Region: "Inazuma", Gender: "Female", Version: "2.1"},
    "Sethos": {Quality: "4", Element: "Electro", Weapon: "Bow", Region: "Sumeru", Gender: "Male", Version: "4.7"},
    "Shenhe": {Quality: "5", Element: "Cryo", Weapon: "Polearm", Region: "Liyue", Gender: "Female", Version: "2.4"},
    "Shikanoin Heizou": {Quality: "4", Element: "Anemo", Weapon: "Catalyst", Region: "Inazuma", Gender: "Male", Version: "2.1"},
    "Sigewinne": {Quality: "5", Element: "Hydro", Weapon: "Bow", Region: "Fontaine", Gender: "Female", Version: "4.7"},
    "Sucrose": {Quality: "4", Element: "Anemo", Weapon: "Catalyst", Region: "Mondstadt", Gender: "Female", Version: "1.0"},
    "Tartaglia": {Quality: "5", Element: "Hydro", Weapon: "Bow", Region: "Fontaine", Gender: "Male", Version: "1.1"},
    "Thoma": {Quality: "4", Element: "Pyro", Weapon: "Polearm", Region: "Inazuma", Gender: "Male", Version: "2.0"},
    "Tighnari": {Quality: "5", Element: "Dendro", Weapon: "Bow", Region: "Sumeru", Gender: "Male", Version: "3.0"},
    "Traveler": {Quality: "5", Element: "None", Weapon: "Sword", Region: "None", Gender: "Male", Version: "1.0"},
    "Venti": {Quality: "5", Element: "Anemo", Weapon: "Bow", Region: "Mondstadt", Gender: "Male", Version: "1.0"},
    "Wanderer": {Quality: "5", Element: "Anemo", Weapon: "Catalyst", Region: "Inazuma", Gender: "Male", Version: "3.3"},
    "Wriothesley": {Quality: "5", Element: "Cryo", Weapon: "Catalyst", Region: "Fontaine", Gender: "Male", Version: "4.1"},
    "Xiangling": {Quality: "4", Element: "Pyro", Weapon: "Polearm", Region: "Mondstadt", Gender: "Female", Version: "1.0"},
    "Xianyun": {Quality: "5", Element: "Anemo", Weapon: "Catalyst", Region: "Liyue", Gender: "Female", Version: "4.4"},
    "Xiao": {Quality: "5", Element: "Anemo", Weapon: "Polearm", Region: "Liyue", Gender: "Male", Version: "1.3"},
    "Xilonen": {Quality: "5", Element: "Geo", Weapon: "Sword", Region: "Natlan", Gender: "Female", Version: "5.1"},
    "Xingqiu": {Quality: "4", Element: "Hydro", Weapon: "Sword", Region: "Liyue", Gender: "Male", Version: "1.2"},
    "Xinyan": {Quality: "4", Element: "Pyro", Weapon: "Claymore", Region: "Liyue", Gender: "Female", Version: "1.1"},
    "Yae Miko": {Quality: "5", Element: "Electro", Weapon: "Catalyst", Region: "Inazuma", Gender: "Female", Version: "2.5"},
    "Yanfei": {Quality: "4", Element: "Pyro", Weapon: "Catalyst", Region: "Liyue", Gender: "Female", Version: "1.5"},
    "Yaoyao": {Quality: "4", Element: "Dendro", Weapon: "Polearm", Region: "Liyue", Gender: "Female", Version: "3.4"},
    "Yelan": {Quality: "5", Element: "Hydro", Weapon: "Bow", Region: "Liyue", Gender: "Female", Version: "2.7"},
    "Yoimiya": {Quality: "5", Element: "Pyro", Weapon: "Bow", Region: "Inazuma", Gender: "Female", Version: "2.0"},
    "Yun Jin": {Quality: "4", Element: "Geo", Weapon: "Polearm", Region: "Liyue", Gender: "Female", Version: "2.4"},
    "Zhongli": {Quality: "5", Element: "Geo", Weapon: "Polearm", Region: "Liyue", Gender: "Male", Version: "1.1"}
};